# Generated by Django 5.0.1 on 2024-01-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weaver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('universe', models.CharField(max_length=50)),
                ('enemies', models.TextField(max_length=250)),
            ],
        ),
    ]
