# Generated by Django 5.0.1 on 2024-01-16 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('weaver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.weaver')),
            ],
        ),
    ]
